# config.yaml
apprise:
  notify:
    incomplete-activity:
      enabled: True # True or False
      ignore:
        - Get 50 entries plus 1000 points!
        - Safeguard your family's info
        - Get Spotify Premium for free
        - A new web hero
    uncaught-exception:
      enabled: True # True or False
    login-code:
      enabled: True # True or False
  summary: ALWAYS
default:
  geolocation: US # Replace with your country code https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
  language: en # Replace with your language code https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
logging:
  level: INFO # See https://docs.python.org/3/library/logging.html#logging-levels
retries:
  base_delay_in_seconds: 120 # base_delay_in_seconds * 2^max = 14.0625 * 2^6 = 900 = 15 minutes
  max: 4
  strategy: EXPONENTIAL
